name: AtaraxiaWarmup
version: 1.0.0
author: MexLr
main: org.example.ataraxiawarmup.Main
api-version: 1.17
depend: [NoteBlockAPI]
commands:
  item:
    aliases: [i, giveitem]
  spawner:
    aliases: []
  spawnentity:
    aliases: [spawnmob]
  trailapplier:
    aliases: [proj, projectile, projectiletrail, projectiletrailapplier, projapplier, projectileapplier, projtrailapplier]
  craft:
    aliases: []
  ingredientsfor:
    aliases: [recipe]
  viewrecipe:
    aliases: []
  applyability:
    aliases: [apply, abilityapplier, abilityanvil, applyanvil, applieranvil]
  spell:
    aliases: []
  warp:
    aliases: []
  startsong:
    aliases: [playsong]
  createspawner:
    aliases: [initspawner, initalizespawner, spawnerhere]
  calccombat:
    aliases: []
  menu:
    aliases: []
  combatlevel:
    aliases: []
  home:
    aliases: []
  shop:
    aliases: []
  playerhead:
    aliases: []
  party:
    aliases: [p]
  chat:
    aliases: [c]
  rotateorders:
    aliases: [rotate]